### ISSUE TITLE
project_video.mp4 is not founded

### ISSUE THREAD

**Issue by leonlee723** [ezzeldeen/ADAS#5]
Hi
   I'm testing advancedLaneDetetion.py. I couludn't find project_video.mp4 in this py file. Please help me, Thanks

**Comment by ezzeldeen** [comment]
you can iterate on each picture as input frames instead of the video frames
the link of the video : https://github.com/SealedSaint/CarND-Term1-P4/blob/master/videos/project_video.mp4?raw=true
